apiVersion: v1
summary: Run Terraform when Pull Request merged in GitHub
description: This workflow runs a Terraform command when a GitHub PR is merged into a configured branch.
homepage: https://github.com/puppetlabs/relay-workflows/tree/master/terraform-continuous-deployment
tags:
  - continuous delivery

triggers:
- name: github-pr-merge
  source:
    type: webhook
    image: relaysh/github-trigger-pull-request-merged:latest
  binding:
    parameters:
      repository: !Data repositorySSHURL
      branch: !Data branch

parameters:
  workspace:
    description: The Terraform workspace to use
    default: default
  moduleDir:
    description: The directory of the Terraform module
    default: .
  repository:
    description: The repository that holds the Terraform module
  branch:
    description: The repository branch to use when cloning the repository
    default: master

steps:
# uncomment the following if you would like to approve the set
# step manually instead of letting it runs automatically.
#
# - name: approval
#   description: Wait for approval to run terraform command
#   type: approval
- name: terraform-run
  image: relaysh/terraform-step-apply
  # dependsOn: [approval]
  spec:
    vars: !Fn.jsonUnmarshal [!Secret terraformVarsJSON]
    workspace: !Parameter workspace
    directory: !Parameter moduleDir
    aws: !Connection { type: aws, name: terraform-state-provider }
    git: !Fn.merge
      connection: !Connection { type: ssh, name: terraform-repository-key }
      name: terraform-plan
      repository: !Parameter repository
      branch: !Parameter branch
