apiVersion: v1
summary: Send a Twilio SMS when PagerDuty incident triggers
description: This workflow uses Twilio to send an SMS notification when a new PagerDuty incident is triggered.
homepage: https://github.com/puppetlabs/relay-workflows/blob/master/pagerduty-to-twilio
tags:
  - incident response

parameters:
  incidentTitle:
    description: a brief summary of the incident
  incidentUrgency:
    description: the urgency of the incident
  incidentURL:
    description: a link to more information about the incident
  serviceName:
    description: the service that triggered the incident

locals:
  message: &message |
    ⚠️ ${parameters.incidentTitle}
    Affected service: ${parameters.serviceName}
    Details: ${parameters.incidentURL}

triggers:
- name: pagerduty
  source:
    type: webhook
    image: relaysh/pagerduty-trigger-incident-triggered
  binding:
    parameters:
      incidentTitle: ${event.title}
      incidentUrgency: ${event.urgency}
      incidentURL: ${event.appURL}
      serviceName: ${event.serviceName}

steps:
- name: notify-via-twilio
  image: relaysh/twilio-step-send-sms
  spec:
    twilio: &twilio
      accountSID: ${secrets.twilioAccountSID}
      authToken: ${secrets.twilioAuthToken}
    from: ${secrets.twilioPhoneNumberFrom}
    to: ${secrets.twilioPhoneNumberTo}
    body: *message
