apiVersion: v1
summary: Connect a Pulumi application in GitHub to Relay for CI/CD
description: >
  This workflow receives webhook events from GitHub and runs Pulumi to preview or create resources in your application.
homepage: https://github.com/relay-integrations/relay-pulumi/tree/master/workflows/pulumi-preview/
tags:
  - continuous delivery

parameters:
  pulumi_backend_url:
    description: Point at a self-hosted Pulumi backend service
  event_payload:
    description: Payload of webhook event, filled in by trigger
  pulumi_commandline:
    description: What to do - only 'preview' (default) or 'up'
    default: preview

triggers:
  - name: github-events
    source:
      type: webhook
      image: relaysh/github-trigger-event-sink
    binding:
      parameters:
        event_payload: !Data event_payload

steps:
  - name: pulumi-run
    image: relaysh/pulumi-step-run
    spec:
      pulumi_access_token: !Secret pulumi_access_token
      github_token: !Secret github_access_token
      pulumi_backend_url: !Parameter pulumi_backend_url
      event_payload: !Parameter event_payload
      pulumi_commandline: !Parameter pulumi_commandline
  - name: slack-output
    image: relaysh/slack-step-message-send
    spec:
      connection: !Connection { type: slack, name: my-workspace }
      channel: prog-relay-testing
      message: !Output {from: pulumi-run, name: output}
      username: relayerbot
